"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { calculateCartTotals, clampQuantity, makeLineId } from "@/lib/cart-utils";
import type { CartLine, CartProductSnapshot, SavedLine, WishlistItem } from "@/types/cart";
import { MiniCart } from "@/components/cart/mini-cart";

type AddOptions = { color?: string; size?: string; quantity?: number };
type CartContextValue = {
  lines: CartLine[]; saved: SavedLine[]; wishlist: WishlistItem[]; coupon: string; hydrated: boolean; totals: ReturnType<typeof calculateCartTotals>;
  addItem: (product: CartProductSnapshot, options?: AddOptions) => void; removeItem: (lineId: string) => void; setQuantity: (lineId: string, quantity: number) => void; saveForLater: (lineId: string) => void; moveSavedToCart: (lineId: string) => void; removeSaved: (lineId: string) => void; toggleWishlist: (product: CartProductSnapshot) => void; removeWishlist: (id: string) => void; moveWishlistToCart: (id: string) => void; isWishlisted: (id: string) => boolean; applyCoupon: (code: string) => { ok: boolean; message: string }; clearCoupon: () => void; clearCart: () => void;
};

const CartContext = createContext<CartContextValue | null>(null);
const STORAGE_KEY = "prakriti-ganesh-commerce-state-v1";
export function CartProvider({ children }: { children: React.ReactNode }) {
  const [lines, setLines] = useState<CartLine[]>([]); const [saved, setSaved] = useState<SavedLine[]>([]); const [wishlist, setWishlist] = useState<WishlistItem[]>([]); const [coupon, setCoupon] = useState(""); const [hydrated, setHydrated] = useState(false); const [miniOpen, setMiniOpen] = useState(false);
  useEffect(() => { try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const parsed = JSON.parse(raw) as { lines?: CartLine[]; saved?: SavedLine[]; wishlist?: WishlistItem[]; coupon?: string }; setLines(Array.isArray(parsed.lines) ? parsed.lines : []); setSaved(Array.isArray(parsed.saved) ? parsed.saved : []); setWishlist(Array.isArray(parsed.wishlist) ? parsed.wishlist : []); setCoupon(typeof parsed.coupon === "string" ? parsed.coupon : ""); } } catch { localStorage.removeItem(STORAGE_KEY); } finally { setHydrated(true); } }, []);
  useEffect(() => { if (!hydrated) return; localStorage.setItem(STORAGE_KEY, JSON.stringify({ lines, saved, wishlist, coupon })); }, [lines, saved, wishlist, coupon, hydrated]);
  const addItem = useCallback((product: CartProductSnapshot, options: AddOptions = {}) => { if (product.stock === "out-of-stock") return; const lineId = makeLineId(product.id, options.color, options.size); setLines((current) => { const found = current.find((line) => line.lineId === lineId); if (found) return current.map((line) => line.lineId === lineId ? { ...line, quantity: clampQuantity(line.quantity + (options.quantity || 1)) } : line); return [...current, { ...product, lineId, quantity: clampQuantity(options.quantity || 1), color: options.color, size: options.size }]; }); setMiniOpen(true); }, []);
  const removeItem = useCallback((lineId: string) => setLines((current) => current.filter((line) => line.lineId !== lineId)), []); const setQuantity = useCallback((lineId: string, quantity: number) => setLines((current) => current.map((line) => line.lineId === lineId ? { ...line, quantity: clampQuantity(quantity) } : line)), []);
  const saveForLater = useCallback((lineId: string) => { const line = lines.find((item) => item.lineId === lineId); if (!line) return; setSaved((items) => [{ ...line, savedAt: new Date().toISOString() }, ...items.filter((item) => item.lineId !== lineId)]); setLines((current) => current.filter((item) => item.lineId !== lineId)); }, [lines]);
  const moveSavedToCart = useCallback((lineId: string) => { const line = saved.find((item) => item.lineId === lineId); if (!line) return; addItem(line, { color: line.color, size: line.size, quantity: line.quantity }); setSaved((current) => current.filter((item) => item.lineId !== lineId)); }, [saved, addItem]);
  const removeSaved = useCallback((lineId: string) => setSaved((current) => current.filter((item) => item.lineId !== lineId)), []); const toggleWishlist = useCallback((product: CartProductSnapshot) => { setWishlist((current) => current.some((item) => item.id === product.id) ? current.filter((item) => item.id !== product.id) : [{ ...product, addedAt: new Date().toISOString() }, ...current]); }, []); const removeWishlist = useCallback((id: string) => setWishlist((current) => current.filter((item) => item.id !== id)), []);
  const moveWishlistToCart = useCallback((id: string) => { const item = wishlist.find((entry) => entry.id === id); if (item) addItem(item); }, [wishlist, addItem]); const isWishlisted = useCallback((id: string) => wishlist.some((item) => item.id === id), [wishlist]);
  const applyCoupon = useCallback((code: string) => { const normalized = code.trim().toUpperCase(); if (!normalized) return { ok: false, message: "Enter a coupon code." }; if (!["GANESH10", "ECO500"].includes(normalized)) return { ok: false, message: "That festival coupon is not available for this cart." }; if (normalized === "ECO500" && calculateCartTotals(lines).subtotal < 4999) return { ok: false, message: "ECO500 needs a cart value of ₹4,999 or more." }; setCoupon(normalized); return { ok: true, message: `${normalized} applied successfully.` }; }, [lines]);
  const clearCoupon = useCallback(() => setCoupon(""), []); const clearCart = useCallback(() => { setLines([]); setCoupon(""); setMiniOpen(false); }, []); const totals = useMemo(() => calculateCartTotals(lines, coupon), [lines, coupon]);
  const value = useMemo<CartContextValue>(() => ({ lines, saved, wishlist, coupon, hydrated, totals, addItem, removeItem, setQuantity, saveForLater, moveSavedToCart, removeSaved, toggleWishlist, removeWishlist, moveWishlistToCart, isWishlisted, applyCoupon, clearCoupon, clearCart }), [lines, saved, wishlist, coupon, hydrated, totals, addItem, removeItem, setQuantity, saveForLater, moveSavedToCart, removeSaved, toggleWishlist, removeWishlist, moveWishlistToCart, isWishlisted, applyCoupon, clearCoupon, clearCart]);
  return <CartContext.Provider value={value}>{children}<MiniCart open={miniOpen} onClose={() => setMiniOpen(false)} /></CartContext.Provider>;
}
export function useCart() { const value = useContext(CartContext); if (!value) throw new Error("useCart must be used inside CartProvider"); return value; }
