import type { Category, Product } from "@/types/commerce";

const ganeshWorkshop = "https://images.unsplash.com/photo-1753545245731-1f37d75d891a?auto=format&fit=crop&w=1000&q=84";
const clayGanesh = "https://images.unsplash.com/photo-1622033482784-86c436688b36?auto=format&fit=crop&w=1000&q=84";
const festiveGanesh = "https://images.unsplash.com/photo-1769326309581-7419e22c6eee?auto=format&fit=crop&w=1000&q=84";
const offeringGanesh = "https://images.unsplash.com/photo-1773473641016-16da4d0ff6d6?auto=format&fit=crop&w=1000&q=84";
const garlandGanesh = "https://images.unsplash.com/photo-1769326309527-0c6fed6cfe22?auto=format&fit=crop&w=1000&q=84";
const floralGanesh = "https://images.unsplash.com/photo-1756859705339-ca307a80b9ef?auto=format&fit=crop&w=1000&q=84";

export const categories: Category[] = [
  {
    slug: "shadu-mati",
    name: "Shadu Mati",
    eyebrow: "River clay",
    description: "Traditional natural-clay Ganesh murtis made for mindful celebration.",
    image: clayGanesh,
  },
  {
    slug: "seed-ganesh",
    name: "Seed Ganesh",
    eyebrow: "Plant after visarjan",
    description: "Eco-minded murtis designed around a greener post-festival ritual.",
    image: ganeshWorkshop,
  },
  {
    slug: "home-murtis",
    name: "Home Murtis",
    eyebrow: "Compact sizes",
    description: "Beautiful smaller murtis for apartments, homes and intimate celebrations.",
    image: floralGanesh,
  },
  {
    slug: "premium",
    name: "Premium",
    eyebrow: "Artisan detail",
    description: "Statement pieces with richer hand-finishing and festive detailing.",
    image: garlandGanesh,
  },
  {
    slug: "natural-finish",
    name: "Natural Finish",
    eyebrow: "Minimal colour",
    description: "Earthy clay-forward designs that keep the handmade texture visible.",
    image: offeringGanesh,
  },
  {
    slug: "bulk-orders",
    name: "Bulk Orders",
    eyebrow: "Societies & gifting",
    description: "Larger quantity planning for societies, offices, events and community groups.",
    image: festiveGanesh,
  },
];

export const featuredProducts: Product[] = [
  {
    id: "prd_001",
    slug: "shree-shadu-ganesh-12",
    name: "Shree Shadu Ganesh — 12 inch",
    brand: "Prakriti Studio",
    category: "shadu-mati",
    price: 1499,
    compareAtPrice: 1899,
    rating: 4.9,
    reviews: 184,
    badge: "Bestseller",
    image: clayGanesh,
    colors: ["Natural Clay", "Soft Festive"],
  },
  {
    id: "prd_002",
    slug: "bal-ganesh-home-8",
    name: "Bal Ganesh Home Murti — 8 inch",
    brand: "Prakriti Studio",
    category: "home-murtis",
    price: 899,
    compareAtPrice: 1099,
    rating: 4.8,
    reviews: 126,
    badge: "Home favourite",
    image: floralGanesh,
    colors: ["Natural", "Terracotta"],
  },
  {
    id: "prd_003",
    slug: "vriksha-seed-ganesh-10",
    name: "Vriksha Seed Ganesh — 10 inch",
    brand: "Prakriti Earth",
    category: "seed-ganesh",
    price: 1299,
    compareAtPrice: 1599,
    rating: 4.8,
    reviews: 92,
    badge: "Eco pick",
    image: ganeshWorkshop,
    colors: ["Earth", "Natural"],
  },
  {
    id: "prd_004",
    slug: "rajadhiraj-premium-18",
    name: "Rajadhiraj Premium Ganesh — 18 inch",
    brand: "Prakriti Artisan",
    category: "premium",
    price: 3499,
    compareAtPrice: 4299,
    rating: 4.9,
    reviews: 78,
    badge: "Premium",
    image: garlandGanesh,
    colors: ["Festive", "Saffron"],
  },
  {
    id: "prd_005",
    slug: "nirmiti-natural-ganesh-11",
    name: "Nirmiti Natural Clay Ganesh — 11 inch",
    brand: "Prakriti Earth",
    category: "natural-finish",
    price: 1199,
    compareAtPrice: 1499,
    rating: 4.7,
    reviews: 64,
    image: offeringGanesh,
    colors: ["Raw Clay"],
  },
  {
    id: "prd_006",
    slug: "siddhivinayak-shadu-15",
    name: "Siddhivinayak Shadu Ganesh — 15 inch",
    brand: "Prakriti Studio",
    category: "shadu-mati",
    price: 2299,
    compareAtPrice: 2799,
    rating: 4.9,
    reviews: 151,
    badge: "Popular",
    image: festiveGanesh,
    colors: ["Festive", "Natural Clay"],
  },
  {
    id: "prd_007",
    slug: "modak-ganesh-mini-6",
    name: "Modak Ganesh Mini — 6 inch",
    brand: "Prakriti Studio",
    category: "home-murtis",
    price: 599,
    compareAtPrice: 749,
    rating: 4.7,
    reviews: 203,
    badge: "New",
    image: floralGanesh,
    colors: ["Natural", "Soft Red"],
  },
  {
    id: "prd_008",
    slug: "samuhik-ganesh-24",
    name: "Samuhik Eco Ganesh — 24 inch",
    brand: "Prakriti Artisan",
    category: "bulk-orders",
    price: 5499,
    compareAtPrice: 6499,
    rating: 4.8,
    reviews: 41,
    image: ganeshWorkshop,
    colors: ["Custom Finish"],
  },
];
